export const passiveSecurityCategories = [
  'transport',
  'response-policy',
  'frame-protection',
  'technology-disclosure',
  'cookie',
  'request-inventory',
  'infrastructure'
] as const;

export type PassiveSecurityCategory =
  typeof passiveSecurityCategories[number];

export type PassiveSecurityPosture =
  | 'misconfiguration'
  | 'defense-in-depth-gap'
  | 'informational';

export type PassiveSecuritySeverity =
  | 'medium'
  | 'low'
  | 'info';

export type PassiveSecurityConfidence =
  | 'high'
  | 'medium'
  | 'low';

export type PassiveSecurityObservationReference =
  `security-observation-${number}`;

export const selectedSecurityHeaderNames = [
  'strict-transport-security',
  'content-security-policy',
  'content-security-policy-report-only',
  'x-content-type-options',
  'referrer-policy',
  'permissions-policy',
  'x-frame-options',
  'server',
  'x-powered-by',
  'content-type'
] as const;

export type SelectedSecurityHeaderName =
  typeof selectedSecurityHeaderNames[number];

export type SelectedSecurityHeaders =
  Partial<
    Record<
      SelectedSecurityHeaderName,
      string[]
    >
  >;

export interface PassiveRedirectEvidence {
  requestedUrl: string;
  responseUrl: string;
  status: number;
  location: string | null;
}

export interface PassivePageSecuritySnapshot {
  requestedUrl: string;
  finalUrl: string;
  responseUrl: string;
  responseStatus: number | null;
  responseReceived: boolean;
  finalScheme: 'http:' | 'https:';
  origin: string;
  pageTitle: string;
  redirects: PassiveRedirectEvidence[];
  headers: SelectedSecurityHeaders;
}

export type PassiveSecurityEvidenceKind =
  | 'transport'
  | 'response-header';

export interface PassiveSecurityEvidence {
  kind: PassiveSecurityEvidenceKind;
  subject: string;
  summary: string;
  headerName?:
    SelectedSecurityHeaderName;
  headerValues?: string[];
}

export interface PassiveSecurityOccurrence {
  pageUrl: string;
  pageTitle: string;
  responseUrl: string;
  evidence: PassiveSecurityEvidence[];
}

export interface PassiveSecurityScope {
  type:
    | 'origin'
    | 'host'
    | 'page'
    | 'response';
  key: string;
}

export interface PassiveSecurityObservation {
  observationReference:
    PassiveSecurityObservationReference;
  fingerprint: string;
  code: string;
  category:
    PassiveSecurityCategory;
  posture:
    PassiveSecurityPosture;
  severity:
    PassiveSecuritySeverity;
  confidence:
    PassiveSecurityConfidence;
  source:
    'deterministic-passive';
  scope:
    PassiveSecurityScope;
  subject: string;
  title: string;
  description: string;
  remediation: string | null;
  occurrences:
    PassiveSecurityOccurrence[];
}

export interface PassiveSecuritySummary {
  observationsCount: number;
  bySeverity: {
    medium: number;
    low: number;
    info: number;
  };
  byCategory:
    Record<
      PassiveSecurityCategory,
      number
    >;
  originsObserved: number;
}

export interface PassiveSecurityReport {
  mode:
    'passive-observation-only';
  disclaimer: string;
  pageSnapshots:
    PassivePageSecuritySnapshot[];
  observations:
    PassiveSecurityObservation[];
  summary:
    PassiveSecuritySummary;
}

export const passiveSecurityDisclaimer =
  'CheckQuest observed response and browser signals generated by normal browsing. It did not perform penetration testing or active vulnerability probing.';
